sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=2f9bf253ef3487d24d1028eaee27bb105be5c5c31815749606612522a4ff1647
language: ruby
rvm:
  - 2.2
  - 2.6
  - 2.7
gemfile:
  - gemfiles/Gemfile
matrix:
  include:
    - dist: trusty
      rvm: 1.8.7
      gemfile: gemfiles/ruby_1_8_7.gemfile
before_install:
  - if `ruby -e 'exit(RUBY_VERSION.to_f < 2.7)'`; then
      gem i rubygems-update -v '< 3' && update_rubygems;
      gem install bundler -v '< 2';
    fi
  - gem --version
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
